/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cripac_isee_alg_pedestrian_attr_DeepMARCaffeNative */

#ifndef _Included_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffeNative
#define _Included_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cripac_isee_alg_pedestrian_attr_DeepMARCaffeNative
 * Method:    initialize
 * Signature: (ILjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffeNative_initialize
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     org_cripac_isee_alg_pedestrian_attr_DeepMARCaffeNative
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffeNative_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cripac_isee_alg_pedestrian_attr_DeepMARCaffeNative
 * Method:    recognize
 * Signature: (J[F[F)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffeNative_recognize
  (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
