/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native */

#ifndef _Included_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native
#define _Included_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native
 * Method:    initialize
 * Signature: (ILjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native_initialize
    (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native_free
    (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native
 * Method:    recognize
 * Signature: (J[F[F)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native_recognize__J_3F_3F
    (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray);

/*
 * Class:     org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native
 * Method:    recognize
 * Signature: (J[[F[[F)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_alg_pedestrian_attr_DeepMARCaffe2Native_recognize__J_3_3F_3_3F
    (JNIEnv *, jobject, jlong, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
